# Generated by Django 2.2.5 on 2020-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to='item/%Y/%m/%d'),
        ),
    ]
